#!/bin/bash

# Generate a unique 16 character alphanumeric string to ensure unique resource names
uniqueId=$(env LC_CTYPE=C tr -dc 'a-z0-9' < /dev/urandom | fold -w 16 | head -n 1)

# Set variables for the new SQL API account, database, and container
resourceGroupName='myResourceGroup-'$uniqueId
location='southcentralus'
accountName='mycosmosaccount-'$uniqueId #needs to be lower case


# Create a resource group
az group create \
    --name $resourceGroupName \
    --location $location


# Create a SQL API Cosmos DB account with session consistency and multi-master enabled
az cosmosdb create \
    --resource-group $resourceGroupName \
    --name $accountName \
    --kind GlobalDocumentDB \
    --locations "South Central US"=0 "North Central US"=1 \
    --default-consistency-level "Session" \
    --enable-multiple-write-locations true


# Get the connection string with Primary Key for Cosmos DB account
endpoint=$(az cosmosdb show -g $myRG -n $myDB --query 'documentEndpoint' -o tsv)
key=$(az cosmosdb list-keys -g $myRG -n $myDB --query 'primaryMasterKey' -o tsv)
connection="AccountEndpoint=$endpoint/;AccountKey=$key;"
echo $connection
